-- ===============================
-- Backup Audit Table Logging
-- ===============================

-- Create table in a DBA utility schema
CREATE TABLE backup_audit_log (
  backup_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  backup_type      VARCHAR2(50),
  status           VARCHAR2(20),
  log_file         VARCHAR2(500),
  backup_start     DATE,
  backup_end       DATE,
  hostname         VARCHAR2(100),
  remarks          VARCHAR2(1000),
  CONSTRAINT pk_backup_audit PRIMARY KEY (backup_id)
);

-- Insert log entry from SQL*Plus after backup (example):
INSERT INTO backup_audit_log (
  backup_type, status, log_file, backup_start, backup_end, hostname, remarks
) VALUES (
  'FULL', 'SUCCESS', '/u01/logs/full_backup_20250619.log',
  SYSDATE, SYSDATE, SYS_CONTEXT('USERENV','HOST'), 'Daily full backup'
);
COMMIT;

-- Add similar insert logic to validate_db.sh, archive_backup.sh, etc. using SQL*Plus
-- END OF TOOLKIT