SELECT * FROM DBA_TAB_PRIVS;

SELECT * FROM ALL_TAB_PRIVS;


SELECT
      OWNER
    , TABLE_NAME
    , SELECT_PRIV
    , INSERT_PRIV
    , DELETE_PRIV
    , UPDATE_PRIV
    , REFERENCES_PRIV
    , ALTER_PRIV
    , INDEX_PRIV
FROM
    TABLE_PRIVILEGES
WHERE
    TABLE_NAME LIKE '%EMPLOYEE%'
;